languague: csharp
solution: ./travis_test/travis_test.sln
mono:
        - latest
        - 3.12.0
        - 3.10.0
install:
        - nuget restore ./travis_test/travis_test.sln
script:
        - msbuild /p:Configuration=Release ./travis_test/travis_test.sln
